vim.cmd("command! ClearCache :!docker-compose exec --user www-data -T php php bin/console cache:clear")
vim.cmd([[command! Copy :'<,'>"+y]])
vim.cmd("command! DeleteFile :call delete(expand('%')) | bdelete!")
vim.cmd("command! ElasticaPopulate :!docker-compose exec --user www-data -T php php bin/console fos:elastica:populate")
vim.cmd("command! FixPermissions :!docker-compose exec -T php chown www-data:$(id -u) -R var/ vendor/ public/ composer.lock composer.json symfony.lock")
vim.cmd([[command! FixWhitespace :%s/\s\+$//e]])
vim.cmd("command! GAmmend :Git commit --amend --verbose")
vim.cmd("command! GimmePermission :call v:lua.require('caesar.functions').gimmePermission()")
vim.cmd("command! GCommit :Git commit --verbose")
vim.cmd("command! GenerateRoutes :!docker-compose exec --user www-data -T php php bin/console fos:js-routing:dump --format=json --target=public/js/fos_js_routes.json")
vim.cmd("command! JsonPrettify :%!jq '.'")
vim.cmd("command! JsonUglify :%!jq --compact-output '.'")
vim.cmd("command! MakeItFast :!xset r rate 200 40")
vim.cmd("command! PgFormat :%!pg_format -B -g -L -b -e -")
vim.cmd("command! RebaseCurrentBranch :lua require('caesar.functions').rebaseCurrentBranch()")
vim.cmd("command! RemoveUnusedClasses :!php-cs-fixer fix '%' --rules=no_unused_imports")
vim.cmd("command! RelatorioGerar :!docker-compose exec --user www-data -T php php bin/console relatorio:gerar")
vim.cmd("command! ReviseCode :Git diff develop HEAD")
vim.cmd([[command! -range SortByLineLength :'<,'>!awk '{ print length(), $0 | "sort -n | cut -d\\  -f2-" }']])
